<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>InterloperHudPro</RootNamespace>
		<LangVersion>Latest</LangVersion>
		<IsPackable>false</IsPackable>
		<AssemblyVersion>1.4.1.0</AssemblyVersion>
		<FileVersion>1.4.1.0</FileVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
		<AssemblyName>InterloperHudPro</AssemblyName>
		<Platforms>AnyCPU;x64;x64</Platforms>
		<OutputType>Library</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<DebugType>none</DebugType>
	</PropertyGroup>

	<PropertyGroup>
		<TheLongDarkPath>D:\SteamLibrary\steamapps\common\TheLongDark</TheLongDarkPath>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="ModSettings">
			<HintPath>$(TheLongDarkPath)\Mods\ModSettings.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="STBlade.Modding.TLD.Il2CppAssemblies.Windows" Version="2.51.0" />
		<PackageReference Include="STBlade.Modding.TLD.ModSettings" Version="1.9.0" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="System.Reflection" />
		<Using Include="System.Diagnostics.CodeAnalysis" />
		<Using Include="Il2Cpp" />
		<Using Include="HarmonyLib" />
		<Using Include="MelonLoader" />
		<Using Include="UnityEngine" />
		<Using Include="ModSettings" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(TheLongDarkPath)\Mods" />
	</Target>
</Project>